### ISSUE TITLE
Support for Custom Post Types

### ISSUE THREAD

**Issue by pottedmeat** [justintadlock/series#4]
I'd like to be able to add a series to my `'podcast'` post type.

I've done so locally by creating a `'series/get_post_types'` filter in `functions-options.php` and using it in `register_taxonomies` in `functions-taxonomies.php`.

**Comment by pottedmeat** [comment]
I'd be happy to submit this as a PR.

**Comment by justintadlock** [comment]
If registering a CPT of your own making, simply use the `taxonomies` parameter of `register_post_type()`.  See: https://developer.wordpress.org/reference/functions/register_post_type/

If needing this for a CPT created by a third-party plugin, use the `register_taxonomy_for_object_type()` function: https://developer.wordpress.org/reference/functions/register_taxonomy_for_object_type/

There's no need to change anything in the Series plugin itself.

**Comment by pottedmeat** [comment]
What would I pass to the `taxonomies` parameter?

**Comment by mallardduck** [comment]
@justintadlock Wondering about this one myself - I assumed it would be better for the plugin to support CPTs itself. For example, a filter/hook within the plugin that allows more post types to be supported.

If w use the suggested method, what name should be passed to `taxonomies`?

**Comment by mallardduck** [comment]
@pottedmeat @justintadlock NVM I figured it out.

@pottedmeat You can just add `'series'` to your taxonomy array. The one hangup is that you need to register your CPT after the plugin registers the taxonomy - the lowest priority you can use is `10`.

Here's what I'm using:

	add_action( 'init', '_my_custom_post_type', 10 );

Initially I had the following which did not work:

	add_action( 'init', 'goodcompany_post_type', 0 );
